name: SCP files to remote server
on: [push]
jobs:
  build:
    name: Push files to remote server
    runs-on: ubuntu-latest
    steps:
      - run: echo "IP_ADDRESS=$(nslookup ${{secrets.HOST}} | grep 'Address:' | awk 'NR==2 {print $NF}')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "${{ env.IP_ADDRESS }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "app.py"
          target: "~/Desktop/website"

  another_job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "IP_ADDRESS=$(nslookup ${{secrets.HOST}} | grep 'Address:' | awk 'NR==2 {print $NF}')" >> $GITHUB_ENV
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ env.IP_ADDRESS }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: sudo systemctl restart start_app.service
