name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=ip_address::$(nslookup www.timowenz.com | grep "Address:" | awk 'NR==2 {print $NF}')"
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.save_ip.outputs.ip_address }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "README.md"
          target: "~/Desktop"
